"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const user_controller_1 = require("../controller/user.controller");
const auth_1 = require("../middleware/auth");
const userRouter = express_1.default.Router();
userRouter.post('/registration', user_controller_1.registrationUser);
userRouter.post('/activate-user', user_controller_1.activateUser);
userRouter.post('/user-login', user_controller_1.loginUser);
userRouter.post('/socialAuth', user_controller_1.socialAuth);
userRouter.get('/user-logout', auth_1.isAuthenticated, user_controller_1.logoutUser);
userRouter.get('/refreshToken', user_controller_1.updateAccessToken);
userRouter.get('/me', auth_1.isAuthenticated, user_controller_1.getUserInfo);
userRouter.post('/update-user-info', auth_1.isAuthenticated, user_controller_1.updateUserInfo);
userRouter.put('/update-user-password', auth_1.isAuthenticated, user_controller_1.updatePassword);
userRouter.get('/get-all-users', auth_1.isAuthenticated, (0, auth_1.authorizeRoles)('admin'), user_controller_1.getAllUsers);
userRouter.put('/update-user-role', auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("admin"), user_controller_1.updateUserRole);
userRouter.delete('/delete-user/:id', auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("admin"), user_controller_1.deleteUser);
exports.default = userRouter;
